<?php
/**
 * POLICY
 *
 * PHP version 5
 *
 * @category Class
 * @package  App\apiModels\travel\v1
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\apiModels\travel\v1\prototypes ;

use \ArrayAccess;
/**
 * POLICY Class Doc Comment
 *
 * @category    Class
 * @description Polisa
 * @package     App\apiModels\travel\v1
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class POLICY extends \App\apiModels\ApiModel implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'calculate' => 'App\apiModels\travel\v1\prototypes\CALCULATE',
        'policy_ref' => 'string',
        'policy_date' => '\DateTime'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'calculate' => 'calculate',
        'policy_ref' => 'policy_ref',
        'policy_date' => 'policy_date'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'calculate' => 'setCalculate',
        'policy_ref' => 'setPolicyRef',
        'policy_date' => 'setPolicyDate'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'calculate' => 'getCalculate',
        'policy_ref' => 'getPolicyRef',
        'policy_date' => 'getPolicyDate'
    );
  
    
    /**
      * $calculate Kalkulacja na podstawie której utworzono polisę
      * @var App\apiModels\travel\v1\prototypes\CALCULATE
      */
    protected $calculate;
    
    /**
      * $policy_ref Identyfikator polisy
      * @var string
      */
    protected $policy_ref;
    
    /**
      * $policy_date Data utworzenia polisy
      * @var \DateTime
      */
    protected $policy_date;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->calculate = $data["calculate"];
            $this->policy_ref = $data["policy_ref"];
            $this->policy_date = $data["policy_date"];
        }
    }
    
    /**
     * Gets calculate
     * @return App\apiModels\travel\v1\prototypes\CALCULATE
     */
    public function getCalculate()
    {
        return $this->calculate;
    }
  
    /**
     * Sets calculate
     * @param App\apiModels\travel\v1\prototypes\CALCULATE $calculate Kalkulacja na podstawie której utworzono polisę
     * @return $this
     */
    public function setCalculate($calculate)
    {
        
        $this->calculate = $calculate;
        return $this;
    }
    
    /**
     * Gets policy_ref
     * @return string
     */
    public function getPolicyRef()
    {
        return $this->policy_ref;
    }
  
    /**
     * Sets policy_ref
     * @param string $policy_ref Identyfikator polisy
     * @return $this
     */
    public function setPolicyRef($policy_ref)
    {
        
        $this->policy_ref = $policy_ref;
        return $this;
    }
    
    /**
     * Gets policy_date
     * @return \DateTime
     */
    public function getPolicyDate()
    {
        return $this->policy_date;
    }
  
    /**
     * Sets policy_date
     * @param \DateTime $policy_date Data utworzenia polisy
     * @return $this
     */
    public function setPolicyDate($policy_date)
    {
        
        $this->policy_date = $policy_date;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
