<?php
/**
 * SOLICITOR
 *
 * PHP version 5
 *
 * @category Class
 * @package  App\apiModels\travel\v1
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\apiModels\travel\v1\prototypes ;

use \ArrayAccess;
/**
 * SOLICITOR Class Doc Comment
 *
 * @category    Class
 * @description OWCA
 * @package     App\apiModels\travel\v1
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SOLICITOR extends \App\apiModels\ApiModel implements ArrayAccess 
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'solicitor_id' => 'string',
        'agent_id' => 'string',
        'permissions' => 'string[]'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'solicitor_id' => 'solicitor_id',
        'agent_id' => 'agent_id',
        'permissions' => 'permissions'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'solicitor_id' => 'setSolicitorId',
        'agent_id' => 'setAgentId',
        'permissions' => 'setPermissions'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'solicitor_id' => 'getSolicitorId',
        'agent_id' => 'getAgentId',
        'permissions' => 'getPermissions'
    );
  
    
    /**
      * $solicitor_id Identyfikator OWCY w rejestrze KNF (tzw numer RA)
      * @var string
      */
    public $solicitor_id;
    
    /**
      * $agent_id Identyfikator Agenta w systemi KNF (tzw numer RA agenta)
      * @var string
      */
    public $agent_id;
    
    /**
      * $permissions Wykorzystane uprawnienia
      * @var string[]
      */
    public $permissions;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->solicitor_id = $data["solicitor_id"];
            $this->agent_id = $data["agent_id"];
            $this->permissions = $data["permissions"];
        }
    }
    
    /**
     * Gets solicitor_id
     * @return string
     */
    public function getSolicitorId()
    {
        return $this->solicitor_id;
    }
  
    /**
     * Sets solicitor_id
     * @param string $solicitor_id Identyfikator OWCY w rejestrze KNF (tzw numer RA)
     * @return $this
     */
    public function setSolicitorId($solicitor_id)
    {
        
        $this->solicitor_id = $solicitor_id;
        return $this;
    }
    
    /**
     * Gets agent_id
     * @return string
     */
    public function getAgentId()
    {
        return $this->agent_id;
    }
  
    /**
     * Sets agent_id
     * @param string $agent_id Identyfikator Agenta w systemi KNF (tzw numer RA agenta)
     * @return $this
     */
    public function setAgentId($agent_id)
    {
        
        $this->agent_id = $agent_id;
        return $this;
    }
    
    /**
     * Gets permissions
     * @return string[]
     */
    public function getPermissions()
    {
        return $this->permissions;
    }
  
    /**
     * Sets permissions
     * @param string[] $permissions Wykorzystane uprawnienia
     * @return $this
     */
    public function setPermissions($permissions)
    {
        
        $this->permissions = $permissions;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
