<?php
/**
 * CalculatePolicyRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  App\apiModels\travel\v2
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\apiModels\travel\v2\Prototypes ;

use \ArrayAccess;
/**
 * CalculatePolicyRequest Class Doc Comment
 *
 * @category    Class
 * @description Zestaw danych do kalkulacji polisy
 * @package     App\apiModels\travel\v2
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CalculatePolicyRequest extends \App\apiModels\ApiModel implements ArrayAccess 
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'quote_id' => 'string',
        'product_id' => 'string',
        'data' => 'App\apiModels\travel\v2\Prototypes\PolicyData',
        'policy_holder' => 'App\apiModels\travel\v2\Prototypes\PolicyHolder',
        'insureds' => 'App\apiModels\travel\v2\Prototypes\Insured[]',
        'possessions' => 'App\apiModels\travel\v2\Prototypes\Possession[]'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'quote_id' => 'quote_id',
        'product_id' => 'product_id',
        'data' => 'data',
        'policy_holder' => 'policy_holder',
        'insureds' => 'insureds',
        'possessions' => 'possessions'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'quote_id' => 'setQuoteId',
        'product_id' => 'setProductId',
        'data' => 'setData',
        'policy_holder' => 'setPolicyHolder',
        'insureds' => 'setInsureds',
        'possessions' => 'setPossessions'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'quote_id' => 'getQuoteId',
        'product_id' => 'getProductId',
        'data' => 'getData',
        'policy_holder' => 'getPolicyHolder',
        'insureds' => 'getInsureds',
        'possessions' => 'getPossessions'
    );
  
    
    /**
      * $quote_id Identyfikator oferty
      * @var string
      */
    public $quote_id;
    
    /**
      * $product_id Identyfikator produktu
      * @var string
      */
    public $product_id;
    
    /**
      * $data 
      * @var App\apiModels\travel\v2\Prototypes\PolicyData
      */
    public $data;
    
    /**
      * $policy_holder 
      * @var App\apiModels\travel\v2\Prototypes\PolicyHolder
      */
    public $policy_holder;
    
    /**
      * $insureds Dane ubezpieczonych
      * @var App\apiModels\travel\v2\Prototypes\Insured[]
      */
    public $insureds;
    
    /**
      * $possessions Mienia
      * @var App\apiModels\travel\v2\Prototypes\Possession[]
      */
    public $possessions;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->quote_id = $data["quote_id"];
            $this->product_id = $data["product_id"];
            $this->data = $data["data"];
            $this->policy_holder = $data["policy_holder"];
            $this->insureds = $data["insureds"];
            $this->possessions = $data["possessions"];
        }
    }
    
    /**
     * Gets quote_id
     * @return string
     */
    public function getQuoteId()
    {
        return $this->quote_id;
    }
  
    /**
     * Sets quote_id
     * @param string $quote_id Identyfikator oferty
     * @return $this
     */
    public function setQuoteId($quote_id)
    {
        
        $this->quote_id = $quote_id;
        return $this;
    }
    
    /**
     * Gets product_id
     * @return string
     */
    public function getProductId()
    {
        return $this->product_id;
    }
  
    /**
     * Sets product_id
     * @param string $product_id Identyfikator produktu
     * @return $this
     */
    public function setProductId($product_id)
    {
        
        $this->product_id = $product_id;
        return $this;
    }
    
    /**
     * Gets data
     * @return App\apiModels\travel\v2\Prototypes\PolicyData
     */
    public function getData()
    {
        return $this->data;
    }
  
    /**
     * Sets data
     * @param App\apiModels\travel\v2\Prototypes\PolicyData $data 
     * @return $this
     */
    public function setData($data)
    {
        
        $this->data = $data;
        return $this;
    }
    
    /**
     * Gets policy_holder
     * @return App\apiModels\travel\v2\Prototypes\PolicyHolder
     */
    public function getPolicyHolder()
    {
        return $this->policy_holder;
    }
  
    /**
     * Sets policy_holder
     * @param App\apiModels\travel\v2\Prototypes\PolicyHolder $policy_holder 
     * @return $this
     */
    public function setPolicyHolder($policy_holder)
    {
        
        $this->policy_holder = $policy_holder;
        return $this;
    }
    
    /**
     * Gets insureds
     * @return App\apiModels\travel\v2\Prototypes\Insured[]
     */
    public function getInsureds()
    {
        return $this->insureds;
    }
  
    /**
     * Sets insureds
     * @param App\apiModels\travel\v2\Prototypes\Insured[] $insureds Dane ubezpieczonych
     * @return $this
     */
    public function setInsureds($insureds)
    {
        
        $this->insureds = $insureds;
        return $this;
    }
    
    /**
     * Gets possessions
     * @return App\apiModels\travel\v2\Prototypes\Possession[]
     */
    public function getPossessions()
    {
        return $this->possessions;
    }
  
    /**
     * Sets possessions
     * @param App\apiModels\travel\v2\Prototypes\Possession[] $possessions Mienia
     * @return $this
     */
    public function setPossessions($possessions)
    {
        
        $this->possessions = $possessions;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
