<?php
/**
 * Policy
 *
 * PHP version 5
 *
 * @category Class
 * @package  App\apiModels\travel\v2
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\apiModels\travel\v2\Prototypes ;

use \ArrayAccess;
/**
 * Policy Class Doc Comment
 *
 * @category    Class
 * @description Polisa
 * @package     App\apiModels\travel\v2
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Policy extends \App\apiModels\ApiModel implements ArrayAccess 
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'policy_id' => 'string',
        'policy_number' => 'string',
        'policy_date' => '\DateTime',
        'premium' => 'App\apiModels\travel\v2\Prototypes\Premium',
        'tariff_premium' => 'App\apiModels\travel\v2\Prototypes\Premium',
        'netto_premium' => 'App\apiModels\travel\v2\Prototypes\Premium',
        'data' => 'App\apiModels\travel\v2\Prototypes\PolicyData',
        'policy_holder' => 'App\apiModels\travel\v2\Prototypes\PolicyHolder',
        'insured' => 'App\apiModels\travel\v2\Prototypes\Insured[]',
        'checksum' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'policy_id' => 'policy_id',
        'policy_number' => 'policy_number',
        'policy_date' => 'policy_date',
        'premium' => 'premium',
        'tariff_premium' => 'tariff_premium',
        'netto_premium' => 'netto_premium',
        'data' => 'data',
        'policy_holder' => 'policy_holder',
        'insured' => 'insured',
        'checksum' => 'checksum'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'policy_id' => 'setPolicyId',
        'policy_number' => 'setPolicyNumber',
        'policy_date' => 'setPolicyDate',
        'premium' => 'setPremium',
        'tariff_premium' => 'setTariffPremium',
        'netto_premium' => 'setNettoPremium',
        'data' => 'setData',
        'policy_holder' => 'setPolicyHolder',
        'insured' => 'setInsured',
        'checksum' => 'setChecksum'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'policy_id' => 'getPolicyId',
        'policy_number' => 'getPolicyNumber',
        'policy_date' => 'getPolicyDate',
        'premium' => 'getPremium',
        'tariff_premium' => 'getTariffPremium',
        'netto_premium' => 'getNettoPremium',
        'data' => 'getData',
        'policy_holder' => 'getPolicyHolder',
        'insured' => 'getInsured',
        'checksum' => 'getChecksum'
    );
  
    
    /**
      * $policy_id Identyfikator polisy
      * @var string
      */
    public $policy_id;
    
    /**
      * $policy_number Numer polisy
      * @var string
      */
    public $policy_number;
    
    /**
      * $policy_date Data zawarcia polisy
      * @var \DateTime
      */
    public $policy_date;
    
    /**
      * $premium Składka pobrana/należna
      * @var App\apiModels\travel\v2\Prototypes\Premium
      */
    public $premium;
    
    /**
      * $tariff_premium Składka wynikająca z taryfy
      * @var App\apiModels\travel\v2\Prototypes\Premium
      */
    public $tariff_premium;
    
    /**
      * $netto_premium Składka netto
      * @var App\apiModels\travel\v2\Prototypes\Premium
      */
    public $netto_premium;
    
    /**
      * $data 
      * @var App\apiModels\travel\v2\Prototypes\PolicyData
      */
    public $data;
    
    /**
      * $policy_holder 
      * @var App\apiModels\travel\v2\Prototypes\PolicyHolder
      */
    public $policy_holder;
    
    /**
      * $insured Dane ubezpieczonych
      * @var App\apiModels\travel\v2\Prototypes\Insured[]
      */
    public $insured;
    
    /**
      * $checksum Suma kontrolna polisy
      * @var string
      */
    public $checksum;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->policy_id = $data["policy_id"];
            $this->policy_number = $data["policy_number"];
            $this->policy_date = $data["policy_date"];
            $this->premium = $data["premium"];
            $this->tariff_premium = $data["tariff_premium"];
            $this->netto_premium = $data["netto_premium"];
            $this->data = $data["data"];
            $this->policy_holder = $data["policy_holder"];
            $this->insured = $data["insured"];
            $this->checksum = $data["checksum"];
        }
    }
    
    /**
     * Gets policy_id
     * @return string
     */
    public function getPolicyId()
    {
        return $this->policy_id;
    }
  
    /**
     * Sets policy_id
     * @param string $policy_id Identyfikator polisy
     * @return $this
     */
    public function setPolicyId($policy_id)
    {
        
        $this->policy_id = $policy_id;
        return $this;
    }
    
    /**
     * Gets policy_number
     * @return string
     */
    public function getPolicyNumber()
    {
        return $this->policy_number;
    }
  
    /**
     * Sets policy_number
     * @param string $policy_number Numer polisy
     * @return $this
     */
    public function setPolicyNumber($policy_number)
    {
        
        $this->policy_number = $policy_number;
        return $this;
    }
    
    /**
     * Gets policy_date
     * @return \DateTime
     */
    public function getPolicyDate()
    {
        return $this->policy_date;
    }
  
    /**
     * Sets policy_date
     * @param \DateTime $policy_date Data zawarcia polisy
     * @return $this
     */
    public function setPolicyDate($policy_date)
    {
        
        $this->policy_date = $policy_date;
        return $this;
    }
    
    /**
     * Gets premium
     * @return App\apiModels\travel\v2\Prototypes\Premium
     */
    public function getPremium()
    {
        return $this->premium;
    }
  
    /**
     * Sets premium
     * @param App\apiModels\travel\v2\Prototypes\Premium $premium Składka pobrana/należna
     * @return $this
     */
    public function setPremium($premium)
    {
        
        $this->premium = $premium;
        return $this;
    }
    
    /**
     * Gets tariff_premium
     * @return App\apiModels\travel\v2\Prototypes\Premium
     */
    public function getTariffPremium()
    {
        return $this->tariff_premium;
    }
  
    /**
     * Sets tariff_premium
     * @param App\apiModels\travel\v2\Prototypes\Premium $tariff_premium Składka wynikająca z taryfy
     * @return $this
     */
    public function setTariffPremium($tariff_premium)
    {
        
        $this->tariff_premium = $tariff_premium;
        return $this;
    }
    
    /**
     * Gets netto_premium
     * @return App\apiModels\travel\v2\Prototypes\Premium
     */
    public function getNettoPremium()
    {
        return $this->netto_premium;
    }
  
    /**
     * Sets netto_premium
     * @param App\apiModels\travel\v2\Prototypes\Premium $netto_premium Składka netto
     * @return $this
     */
    public function setNettoPremium($netto_premium)
    {
        
        $this->netto_premium = $netto_premium;
        return $this;
    }
    
    /**
     * Gets data
     * @return App\apiModels\travel\v2\Prototypes\PolicyData
     */
    public function getData()
    {
        return $this->data;
    }
  
    /**
     * Sets data
     * @param App\apiModels\travel\v2\Prototypes\PolicyData $data 
     * @return $this
     */
    public function setData($data)
    {
        
        $this->data = $data;
        return $this;
    }
    
    /**
     * Gets policy_holder
     * @return App\apiModels\travel\v2\Prototypes\PolicyHolder
     */
    public function getPolicyHolder()
    {
        return $this->policy_holder;
    }
  
    /**
     * Sets policy_holder
     * @param App\apiModels\travel\v2\Prototypes\PolicyHolder $policy_holder 
     * @return $this
     */
    public function setPolicyHolder($policy_holder)
    {
        
        $this->policy_holder = $policy_holder;
        return $this;
    }
    
    /**
     * Gets insured
     * @return App\apiModels\travel\v2\Prototypes\Insured[]
     */
    public function getInsured()
    {
        return $this->insured;
    }
  
    /**
     * Sets insured
     * @param App\apiModels\travel\v2\Prototypes\Insured[] $insured Dane ubezpieczonych
     * @return $this
     */
    public function setInsured($insured)
    {
        
        $this->insured = $insured;
        return $this;
    }
    
    /**
     * Gets checksum
     * @return string
     */
    public function getChecksum()
    {
        return $this->checksum;
    }
  
    /**
     * Sets checksum
     * @param string $checksum Suma kontrolna polisy
     * @return $this
     */
    public function setChecksum($checksum)
    {
        
        $this->checksum = $checksum;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
