<?php
/**
 * QUOTE
 *
 * PHP version 5
 *
 * @category Class
 * @package  App\apiModels\travel\v2
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\apiModels\travel\v2\Prototypes ;

use \ArrayAccess;
/**
 * QUOTE Class Doc Comment
 *
 * @category    Class
 * @description Oferta
 * @package     App\apiModels\travel\v2
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QUOTE extends \App\apiModels\ApiModel implements ArrayAccess 
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'quote_id' => 'string',
        'product_id' => 'string',
        'premium' => 'App\apiModels\travel\v2\Prototypes\PREMIUM',
        'tariff_premium' => 'App\apiModels\travel\v2\Prototypes\PREMIUM',
        'promo_code_valid' => 'bool',
        'description' => 'string',
        'details' => 'App\apiModels\travel\v2\Prototypes\DETAIL[]'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'quote_id' => 'quote_id',
        'product_id' => 'product_id',
        'premium' => 'premium',
        'tariff_premium' => 'tariff_premium',
        'promo_code_valid' => 'promo_code_valid',
        'description' => 'description',
        'details' => 'details'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'quote_id' => 'setQuoteId',
        'product_id' => 'setProductId',
        'premium' => 'setPremium',
        'tariff_premium' => 'setTariffPremium',
        'promo_code_valid' => 'setPromoCodeValid',
        'description' => 'setDescription',
        'details' => 'setDetails'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'quote_id' => 'getQuoteId',
        'product_id' => 'getProductId',
        'premium' => 'getPremium',
        'tariff_premium' => 'getTariffPremium',
        'promo_code_valid' => 'getPromoCodeValid',
        'description' => 'getDescription',
        'details' => 'getDetails'
    );
  
    
    /**
      * $quote_id Identyfikator oferty
      * @var string
      */
    public $quote_id;
    
    /**
      * $product_id Identyfikator produktu
      * @var string
      */
    public $product_id;
    
    /**
      * $premium Składka pobrana/należna
      * @var App\apiModels\travel\v2\Prototypes\PREMIUM
      */
    public $premium;
    
    /**
      * $tariff_premium Składka wynikająca z taryfy
      * @var App\apiModels\travel\v2\Prototypes\PREMIUM
      */
    public $tariff_premium;
    
    /**
      * $promo_code_valid Czy kod promocyjny jest prawidłowy
      * @var bool
      */
    public $promo_code_valid;
    
    /**
      * $description Opis wariantu
      * @var string
      */
    public $description;
    
    /**
      * $details Detale oferty
      * @var App\apiModels\travel\v2\Prototypes\DETAIL[]
      */
    public $details;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->quote_id = $data["quote_id"];
            $this->product_id = $data["product_id"];
            $this->premium = $data["premium"];
            $this->tariff_premium = $data["tariff_premium"];
            $this->promo_code_valid = $data["promo_code_valid"];
            $this->description = $data["description"];
            $this->details = $data["details"];
        }
    }
    
    /**
     * Gets quote_id
     * @return string
     */
    public function getQuoteId()
    {
        return $this->quote_id;
    }
  
    /**
     * Sets quote_id
     * @param string $quote_id Identyfikator oferty
     * @return $this
     */
    public function setQuoteId($quote_id)
    {
        
        $this->quote_id = $quote_id;
        return $this;
    }
    
    /**
     * Gets product_id
     * @return string
     */
    public function getProductId()
    {
        return $this->product_id;
    }
  
    /**
     * Sets product_id
     * @param string $product_id Identyfikator produktu
     * @return $this
     */
    public function setProductId($product_id)
    {
        
        $this->product_id = $product_id;
        return $this;
    }
    
    /**
     * Gets premium
     * @return App\apiModels\travel\v2\Prototypes\PREMIUM
     */
    public function getPremium()
    {
        return $this->premium;
    }
  
    /**
     * Sets premium
     * @param App\apiModels\travel\v2\Prototypes\PREMIUM $premium Składka pobrana/należna
     * @return $this
     */
    public function setPremium($premium)
    {
        
        $this->premium = $premium;
        return $this;
    }
    
    /**
     * Gets tariff_premium
     * @return App\apiModels\travel\v2\Prototypes\PREMIUM
     */
    public function getTariffPremium()
    {
        return $this->tariff_premium;
    }
  
    /**
     * Sets tariff_premium
     * @param App\apiModels\travel\v2\Prototypes\PREMIUM $tariff_premium Składka wynikająca z taryfy
     * @return $this
     */
    public function setTariffPremium($tariff_premium)
    {
        
        $this->tariff_premium = $tariff_premium;
        return $this;
    }
    
    /**
     * Gets promo_code_valid
     * @return bool
     */
    public function getPromoCodeValid()
    {
        return $this->promo_code_valid;
    }
  
    /**
     * Sets promo_code_valid
     * @param bool $promo_code_valid Czy kod promocyjny jest prawidłowy
     * @return $this
     */
    public function setPromoCodeValid($promo_code_valid)
    {
        
        $this->promo_code_valid = $promo_code_valid;
        return $this;
    }
    
    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }
  
    /**
     * Sets description
     * @param string $description Opis wariantu
     * @return $this
     */
    public function setDescription($description)
    {
        
        $this->description = $description;
        return $this;
    }
    
    /**
     * Gets details
     * @return App\apiModels\travel\v2\Prototypes\DETAIL[]
     */
    public function getDetails()
    {
        return $this->details;
    }
  
    /**
     * Sets details
     * @param App\apiModels\travel\v2\Prototypes\DETAIL[] $details Detale oferty
     * @return $this
     */
    public function setDetails($details)
    {
        
        $this->details = $details;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
