<?php
/**
 * Risk
 *
 * PHP version 5
 *
 * @category Class
 * @package  App\apiModels\travel\v2
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\apiModels\travel\v2\Prototypes ;

use \ArrayAccess;
/**
 * Risk Class Doc Comment
 *
 * @category    Class
 * @description Ryzyko
 * @package     App\apiModels\travel\v2
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Risk extends \App\apiModels\ApiModel implements ArrayAccess 
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'code' => 'string',
        'sum_insured' => 'App\apiModels\travel\v2\Prototypes\SumInsured',
        'start_date' => '\DateTime',
        'end_date' => '\DateTime',
        'possessions' => 'App\apiModels\travel\v2\Prototypes\Possession[]'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'code' => 'code',
        'sum_insured' => 'sum_insured',
        'start_date' => 'start_date',
        'end_date' => 'end_date',
        'possessions' => 'possessions'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'code' => 'setCode',
        'sum_insured' => 'setSumInsured',
        'start_date' => 'setStartDate',
        'end_date' => 'setEndDate',
        'possessions' => 'setPossessions'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'code' => 'getCode',
        'sum_insured' => 'getSumInsured',
        'start_date' => 'getStartDate',
        'end_date' => 'getEndDate',
        'possessions' => 'getPossessions'
    );
  
    
    /**
      * $code Kod ryzyka
      * @var string
      */
    public $code;
    
    /**
      * $sum_insured Suma ubezpieczenia
      * @var App\apiModels\travel\v2\Prototypes\SumInsured
      */
    public $sum_insured;
    
    /**
      * $start_date Data rozpoczęcia okresu odpowiedzialności
      * @var \DateTime
      */
    public $start_date;
    
    /**
      * $end_date Data zakończenia okresu odpowiedzialności
      * @var \DateTime
      */
    public $end_date;
    
    /**
      * $possessions Mienia
      * @var App\apiModels\travel\v2\Prototypes\Possession[]
      */
    public $possessions;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->code = $data["code"];
            $this->sum_insured = $data["sum_insured"];
            $this->start_date = $data["start_date"];
            $this->end_date = $data["end_date"];
            $this->possessions = $data["possessions"];
        }
    }
    
    /**
     * Gets code
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }
  
    /**
     * Sets code
     * @param string $code Kod ryzyka
     * @return $this
     */
    public function setCode($code)
    {
        
        $this->code = $code;
        return $this;
    }
    
    /**
     * Gets sum_insured
     * @return App\apiModels\travel\v2\Prototypes\SumInsured
     */
    public function getSumInsured()
    {
        return $this->sum_insured;
    }
  
    /**
     * Sets sum_insured
     * @param App\apiModels\travel\v2\Prototypes\SumInsured $sum_insured Suma ubezpieczenia
     * @return $this
     */
    public function setSumInsured($sum_insured)
    {
        
        $this->sum_insured = $sum_insured;
        return $this;
    }
    
    /**
     * Gets start_date
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->start_date;
    }
  
    /**
     * Sets start_date
     * @param \DateTime $start_date Data rozpoczęcia okresu odpowiedzialności
     * @return $this
     */
    public function setStartDate($start_date)
    {
        
        $this->start_date = $start_date;
        return $this;
    }
    
    /**
     * Gets end_date
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->end_date;
    }
  
    /**
     * Sets end_date
     * @param \DateTime $end_date Data zakończenia okresu odpowiedzialności
     * @return $this
     */
    public function setEndDate($end_date)
    {
        
        $this->end_date = $end_date;
        return $this;
    }
    
    /**
     * Gets possessions
     * @return App\apiModels\travel\v2\Prototypes\Possession[]
     */
    public function getPossessions()
    {
        return $this->possessions;
    }
  
    /**
     * Sets possessions
     * @param App\apiModels\travel\v2\Prototypes\Possession[] $possessions Mienia
     * @return $this
     */
    public function setPossessions($possessions)
    {
        
        $this->possessions = $possessions;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
