<?php
/**
 * PolicyIssueRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  App\apiModels\internal\v2
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\apiModels\internal\v2 ;

use \ArrayAccess;
/**
 * PolicyIssueRequest Class Doc Comment
 *
 * @category    Class
 * @description Potwierdzenie zapisania polisy w systemie docelowym
 * @package     App\apiModels\internal\v2
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PolicyIssueRequest extends \App\apiModels\ApiModel implements ArrayAccess 
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'policy_date' => '\DateTime',
        'policy_number' => 'string',
        'start_date' => '\DateTime',
        'end_date' => '\DateTime',
        'abroad' => 'bool',
        'destination' => 'string',
        'options' => 'App\apiModels\internal\v2\OPTIONVALUE[]',
        'addons' => 'App\apiModels\internal\v2\OPTIONVALUE[]',
        'policy_holder' => 'App\apiModels\internal\v2\POLICYHOLDER',
        'insured' => 'App\apiModels\internal\v2\INSURED[]',
        'premium' => 'App\apiModels\internal\v2\PREMIUM',
        'tariff_premium' => 'App\apiModels\internal\v2\PREMIUM',
        'netto_premium' => 'App\apiModels\internal\v2\PREMIUM',
        'partner' => 'App\apiModels\internal\v2\PARTNER',
        'product' => 'App\apiModels\internal\v2\PRODUCT'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'policy_date' => 'policy_date',
        'policy_number' => 'policy_number',
        'start_date' => 'start_date',
        'end_date' => 'end_date',
        'abroad' => 'abroad',
        'destination' => 'destination',
        'options' => 'options',
        'addons' => 'addons',
        'policy_holder' => 'policy_holder',
        'insured' => 'insured',
        'premium' => 'premium',
        'tariff_premium' => 'tariff_premium',
        'netto_premium' => 'netto_premium',
        'partner' => 'partner',
        'product' => 'product'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'policy_date' => 'setPolicyDate',
        'policy_number' => 'setPolicyNumber',
        'start_date' => 'setStartDate',
        'end_date' => 'setEndDate',
        'abroad' => 'setAbroad',
        'destination' => 'setDestination',
        'options' => 'setOptions',
        'addons' => 'setAddons',
        'policy_holder' => 'setPolicyHolder',
        'insured' => 'setInsured',
        'premium' => 'setPremium',
        'tariff_premium' => 'setTariffPremium',
        'netto_premium' => 'setNettoPremium',
        'partner' => 'setPartner',
        'product' => 'setProduct'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'policy_date' => 'getPolicyDate',
        'policy_number' => 'getPolicyNumber',
        'start_date' => 'getStartDate',
        'end_date' => 'getEndDate',
        'abroad' => 'getAbroad',
        'destination' => 'getDestination',
        'options' => 'getOptions',
        'addons' => 'getAddons',
        'policy_holder' => 'getPolicyHolder',
        'insured' => 'getInsured',
        'premium' => 'getPremium',
        'tariff_premium' => 'getTariffPremium',
        'netto_premium' => 'getNettoPremium',
        'partner' => 'getPartner',
        'product' => 'getProduct'
    );
  
    
    /**
      * $policy_date Data zawarcia polisy
      * @var \DateTime
      */
    public $policy_date;
    
    /**
      * $policy_number Numer polisy
      * @var string
      */
    public $policy_number;
    
    /**
      * $start_date Data rozpoczęcia ochrony
      * @var \DateTime
      */
    public $start_date;
    
    /**
      * $end_date Data zakończenia ochrony
      * @var \DateTime
      */
    public $end_date;
    
    /**
      * $abroad Czy ubezpieczony przebywa za granicą Polski w momencie przystąpienia do ubezpieczenia (informacja ważna ze względu na ewentualną karencję w ochronie ubezpieczeniowej)
      * @var bool
      */
    public $abroad;
    
    /**
      * $destination Cel podróży (kod kraju określony w ISO 3166-1 alpha-2 lub EU - Unia Europejska lub WR - świat)
      * @var string
      */
    public $destination;
    
    /**
      * $options Wybrane opcje dodatkowe
      * @var App\apiModels\internal\v2\OPTIONVALUE[]
      */
    public $options;
    
    /**
      * $addons Dodatkowe atrybuty
      * @var App\apiModels\internal\v2\OPTIONVALUE[]
      */
    public $addons;
    
    /**
      * $policy_holder 
      * @var App\apiModels\internal\v2\POLICYHOLDER
      */
    public $policy_holder;
    
    /**
      * $insured Dane ubezpieczonych
      * @var App\apiModels\internal\v2\INSURED[]
      */
    public $insured;
    
    /**
      * $premium Składka pobrana/należna
      * @var App\apiModels\internal\v2\PREMIUM
      */
    public $premium;
    
    /**
      * $tariff_premium Składka wynikająca z taryfy
      * @var App\apiModels\internal\v2\PREMIUM
      */
    public $tariff_premium;
    
    /**
      * $netto_premium Składka netto
      * @var App\apiModels\internal\v2\PREMIUM
      */
    public $netto_premium;
    
    /**
      * $partner 
      * @var App\apiModels\internal\v2\PARTNER
      */
    public $partner;
    
    /**
      * $product 
      * @var App\apiModels\internal\v2\PRODUCT
      */
    public $product;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->policy_date = $data["policy_date"];
            $this->policy_number = $data["policy_number"];
            $this->start_date = $data["start_date"];
            $this->end_date = $data["end_date"];
            $this->abroad = $data["abroad"];
            $this->destination = $data["destination"];
            $this->options = $data["options"];
            $this->addons = $data["addons"];
            $this->policy_holder = $data["policy_holder"];
            $this->insured = $data["insured"];
            $this->premium = $data["premium"];
            $this->tariff_premium = $data["tariff_premium"];
            $this->netto_premium = $data["netto_premium"];
            $this->partner = $data["partner"];
            $this->product = $data["product"];
        }
    }
    
    /**
     * Gets policy_date
     * @return \DateTime
     */
    public function getPolicyDate()
    {
        return $this->policy_date;
    }
  
    /**
     * Sets policy_date
     * @param \DateTime $policy_date Data zawarcia polisy
     * @return $this
     */
    public function setPolicyDate($policy_date)
    {
        
        $this->policy_date = $policy_date;
        return $this;
    }
    
    /**
     * Gets policy_number
     * @return string
     */
    public function getPolicyNumber()
    {
        return $this->policy_number;
    }
  
    /**
     * Sets policy_number
     * @param string $policy_number Numer polisy
     * @return $this
     */
    public function setPolicyNumber($policy_number)
    {
        
        $this->policy_number = $policy_number;
        return $this;
    }
    
    /**
     * Gets start_date
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->start_date;
    }
  
    /**
     * Sets start_date
     * @param \DateTime $start_date Data rozpoczęcia ochrony
     * @return $this
     */
    public function setStartDate($start_date)
    {
        
        $this->start_date = $start_date;
        return $this;
    }
    
    /**
     * Gets end_date
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->end_date;
    }
  
    /**
     * Sets end_date
     * @param \DateTime $end_date Data zakończenia ochrony
     * @return $this
     */
    public function setEndDate($end_date)
    {
        
        $this->end_date = $end_date;
        return $this;
    }
    
    /**
     * Gets abroad
     * @return bool
     */
    public function getAbroad()
    {
        return $this->abroad;
    }
  
    /**
     * Sets abroad
     * @param bool $abroad Czy ubezpieczony przebywa za granicą Polski w momencie przystąpienia do ubezpieczenia (informacja ważna ze względu na ewentualną karencję w ochronie ubezpieczeniowej)
     * @return $this
     */
    public function setAbroad($abroad)
    {
        
        $this->abroad = $abroad;
        return $this;
    }
    
    /**
     * Gets destination
     * @return string
     */
    public function getDestination()
    {
        return $this->destination;
    }
  
    /**
     * Sets destination
     * @param string $destination Cel podróży (kod kraju określony w ISO 3166-1 alpha-2 lub EU - Unia Europejska lub WR - świat)
     * @return $this
     */
    public function setDestination($destination)
    {
        
        $this->destination = $destination;
        return $this;
    }
    
    /**
     * Gets options
     * @return App\apiModels\internal\v2\OPTIONVALUE[]
     */
    public function getOptions()
    {
        return $this->options;
    }
  
    /**
     * Sets options
     * @param App\apiModels\internal\v2\OPTIONVALUE[] $options Wybrane opcje dodatkowe
     * @return $this
     */
    public function setOptions($options)
    {
        
        $this->options = $options;
        return $this;
    }
    
    /**
     * Gets addons
     * @return App\apiModels\internal\v2\OPTIONVALUE[]
     */
    public function getAddons()
    {
        return $this->addons;
    }
  
    /**
     * Sets addons
     * @param App\apiModels\internal\v2\OPTIONVALUE[] $addons Dodatkowe atrybuty
     * @return $this
     */
    public function setAddons($addons)
    {
        
        $this->addons = $addons;
        return $this;
    }
    
    /**
     * Gets policy_holder
     * @return App\apiModels\internal\v2\POLICYHOLDER
     */
    public function getPolicyHolder()
    {
        return $this->policy_holder;
    }
  
    /**
     * Sets policy_holder
     * @param App\apiModels\internal\v2\POLICYHOLDER $policy_holder 
     * @return $this
     */
    public function setPolicyHolder($policy_holder)
    {
        
        $this->policy_holder = $policy_holder;
        return $this;
    }
    
    /**
     * Gets insured
     * @return App\apiModels\internal\v2\INSURED[]
     */
    public function getInsured()
    {
        return $this->insured;
    }
  
    /**
     * Sets insured
     * @param App\apiModels\internal\v2\INSURED[] $insured Dane ubezpieczonych
     * @return $this
     */
    public function setInsured($insured)
    {
        
        $this->insured = $insured;
        return $this;
    }
    
    /**
     * Gets premium
     * @return App\apiModels\internal\v2\PREMIUM
     */
    public function getPremium()
    {
        return $this->premium;
    }
  
    /**
     * Sets premium
     * @param App\apiModels\internal\v2\PREMIUM $premium Składka pobrana/należna
     * @return $this
     */
    public function setPremium($premium)
    {
        
        $this->premium = $premium;
        return $this;
    }
    
    /**
     * Gets tariff_premium
     * @return App\apiModels\internal\v2\PREMIUM
     */
    public function getTariffPremium()
    {
        return $this->tariff_premium;
    }
  
    /**
     * Sets tariff_premium
     * @param App\apiModels\internal\v2\PREMIUM $tariff_premium Składka wynikająca z taryfy
     * @return $this
     */
    public function setTariffPremium($tariff_premium)
    {
        
        $this->tariff_premium = $tariff_premium;
        return $this;
    }
    
    /**
     * Gets netto_premium
     * @return App\apiModels\internal\v2\PREMIUM
     */
    public function getNettoPremium()
    {
        return $this->netto_premium;
    }
  
    /**
     * Sets netto_premium
     * @param App\apiModels\internal\v2\PREMIUM $netto_premium Składka netto
     * @return $this
     */
    public function setNettoPremium($netto_premium)
    {
        
        $this->netto_premium = $netto_premium;
        return $this;
    }
    
    /**
     * Gets partner
     * @return App\apiModels\internal\v2\PARTNER
     */
    public function getPartner()
    {
        return $this->partner;
    }
  
    /**
     * Sets partner
     * @param App\apiModels\internal\v2\PARTNER $partner 
     * @return $this
     */
    public function setPartner($partner)
    {
        
        $this->partner = $partner;
        return $this;
    }
    
    /**
     * Gets product
     * @return App\apiModels\internal\v2\PRODUCT
     */
    public function getProduct()
    {
        return $this->product;
    }
  
    /**
     * Sets product
     * @param App\apiModels\internal\v2\PRODUCT $product 
     * @return $this
     */
    public function setProduct($product)
    {
        
        $this->product = $product;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
