<?php
/**
 * SmsStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  App\apiModels\internal\v2
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\apiModels\internal\v2 ;

use \ArrayAccess;
/**
 * SmsStatus Class Doc Comment
 *
 * @category    Class
 * @description Potwierdzenie zapisania wiadomości SMS w systemie docelowym
 * @package     App\apiModels\internal\v2
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SmsStatus extends \App\apiModels\ApiModel implements ArrayAccess 
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'message_id' => 'int',
        'message_status' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'message_id' => 'message_id',
        'message_status' => 'message_status'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'message_id' => 'setMessageId',
        'message_status' => 'setMessageStatus'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'message_id' => 'getMessageId',
        'message_status' => 'getMessageStatus'
    );
  
    
    /**
      * $message_id Identyfikator wiadomości SMS w systemie docelowym w systemie docelowym
      * @var int
      */
    public $message_id;
    
    /**
      * $message_status Status wiadomości w systemie docelowym
      * @var string
      */
    public $message_status;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->message_id = $data["message_id"];
            $this->message_status = $data["message_status"];
        }
    }
    
    /**
     * Gets message_id
     * @return int
     */
    public function getMessageId()
    {
        return $this->message_id;
    }
  
    /**
     * Sets message_id
     * @param int $message_id Identyfikator wiadomości SMS w systemie docelowym w systemie docelowym
     * @return $this
     */
    public function setMessageId($message_id)
    {
        
        $this->message_id = $message_id;
        return $this;
    }
    
    /**
     * Gets message_status
     * @return string
     */
    public function getMessageStatus()
    {
        return $this->message_status;
    }
  
    /**
     * Sets message_status
     * @param string $message_status Status wiadomości w systemie docelowym
     * @return $this
     */
    public function setMessageStatus($message_status)
    {
        $allowed_values = array("NEW", "SEND", "CANCELED");
        if (!in_array($message_status, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'message_status', must be one of 'NEW', 'SEND', 'CANCELED'");
        }
        $this->message_status = $message_status;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
